name: Build Rust Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Install protoc
        run: |
          # TODO: use action to install protoc, requires GH token
          sudo apt-get install protobuf-compiler

      - name: Build the Rust code
        run: |
          cd rust
          cargo build --verbose

